set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property PACKAGE_PIN V17 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]

set_property PACKAGE_PIN W7 [get_ports seg_output[0]]
set_property PACKAGE_PIN W6 [get_ports seg_output[1]]
set_property PACKAGE_PIN U8 [get_ports seg_output[2]]
set_property PACKAGE_PIN V8 [get_ports seg_output[3]]
set_property PACKAGE_PIN U5 [get_ports seg_output[4]]
set_property PACKAGE_PIN V5 [get_ports seg_output[5]]
set_property PACKAGE_PIN U7 [get_ports seg_output[6]]
set_property PACKAGE_PIN V7 [get_ports seg_output[7]]
set_property IOSTANDARD LVCMOS33 [get_ports seg_output]
set_property PACKAGE_PIN W4 [get_ports an_output[0]]
set_property PACKAGE_PIN V4 [get_ports an_output[1]]
set_property PACKAGE_PIN U4 [get_ports an_output[2]]
set_property PACKAGE_PIN U2 [get_ports an_output[3]]
set_property IOSTANDARD LVCMOS33 [get_ports an_output]